spring.application.name=KitchenGrande

server.port=8080


spring.datasource.url=jdbc:mysql://caboose.proxy.rlwy.net:19458/railway?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=FPknxipySlxMbhdmrKUebIvQxaYqsIwT
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update

# Dialect tells Hibernate how to speak MySQL's version of SQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Show SQL queries in the console (useful for debugging during development)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


spring.web.resources.static-locations=classpath:/static/
